### ISSUE TITLE
Chrom.txt format

### ISSUE THREAD

**Issue by KenWifi** [PRIDE-Toolsuite/PGConverter#7]
Hi,

I am not sure what's the exact format of the Chrom.txt file. Can you tell me what's the meaning of this parameter and provide an example? 

Best regards.

Kai

**Comment by Tobias-Ternent** [comment]
Hi Kai,

For the Chrom.txt file - listing the chromosome sizes - please see the UCSC documentation about this for further details https://genome.ucsc.edu/goldenpath/help/bigBed.html which has some examples. This type of file is essentially plain text, two columns: one for the chromosome name, another for its total size.

There's some more details on the PSI website for proBed, and in the specificiation document: http://www.psidev.info/probed#

Basically, for conversion to bigBed, from whatever BED file not just proBed, a chromosome sizes file needs to be provided when used with UCSC's bed2bigbed program. And with this in mind, if a BED file has chromsomes present that are not listed in the sizes file, then generating bigBed files would fail. Sif you provide the chromosome sizes file during proBed generation, then hopefully it should help ensure compatability to convert to bigBed. The bigBed format is important, because genome browsers are much better suited  to it (better performance) than a regular BED file.

Tobias

**Comment by KenWifi** [comment]
Got it 👍! Thanks very much.
